name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.2.0
        with:
          node-version: "15.x"

      - run: npm i -g pnpm
      - run: pnpm install
      - run: pnpm install:monobundle
      - run: pnpm test

      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage/clover.xml
          fail_ci_if_error: true
